---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.7/manifests/install.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    path: repo-server.patch.yml

images:
  - name: quay.io/argoproj/argocd
    newName: ghcr.io/ftsell/argocd-git-crypt

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: argocd-gpg-secret-keys
    files:
      - key_fingerprint=gpg.key
